In [1]:
import pandas as pd

# Load the Titan Company Excel file
titan_file = pd.ExcelFile("Titan Company.xlsx")

# See all sheet names
print(titan_file.sheet_names)

['Profit & Loss', 'Quarters', 'Balance Sheet', 'Cash Flow', 'Customization', 'Data Sheet']

In [2]:
profit_loss = pd.read_excel("Titan company.xlsx", sheet_name ="Profit & Loss")
balance_sheet = pd.read_excel("Titan company.xlsx", sheet_name ="Balance Sheet")
cash_flow = pd.read_excel("Titan company.xlsx", sheet_name ="Cash Flow")

print("All sheets loaded successfully !!!")

All sheets loaded successfully !!!

In [3]:
print("Profit & Loss Sheet")
print("Shape:", profit_loss.shape)
print()
profit_loss.head(10)

Profit & Loss Sheet
Shape: (24, 14)

,TITAN COMPANY LTD,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,SCREENER.IN,Unnamed: 13
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Narration,2017-03-31 00:00:00,2018-03-31 00:00:00,2019-03-31 00:00:00,2020-03-31 00:00:00,2021-03-31 00:00:00,2022-03-31 00:00:00,2023-03-31 00:00:00,2024-03-31 00:00:00,2025-03-31 00:00:00,2026-03-31 00:00:00,Trailing,Best Case,Worst Case
2,Sales,13260.83,16119.77,19778.52,21052,21644,28799,40575,51084,60456,87584,87584,126884.958581,108023.855123
3,Expenses,12096.93,14475.57,17784.73,18589,19919,25455,35693,45792,54762,79227,79228,114559.293399,97717.779431
4,Operating Profit,1163.9,1644.2,1993.79,2463,1725,3344,4882,5292,5694,8357,8356,12325.665183,10306.075692
5,Other Income,-42.38,69.93,178.48,153,180,177,306,534,487,450,452,0,0
6,Depreciation,110.53,131.43,162.84,348,375,399,441,584,693,826,826,826,826
7,Interest,37.74,52.92,52.54,166,203,218,300,619,953,1180,1180,1180,1180
8,Profit before tax,973.25,1529.78,1956.89,2102,1327,2904,4447,4623,4535,6801,6802,10319.665183,8300.075692
9,Tax,275.97,427.87,568.24,609,353,706,1173,1127,1198,1728,1728,0.254043,0.254043

In [4]:
# Read Profit & Loss sheet properly
profit_loss = pd.read_excel("Titan Company.xlsx", sheet_name="Profit & Loss",header=2)

profit_loss.head(5)

,Narration,2017-03-31 00:00:00,2018-03-31 00:00:00,2019-03-31 00:00:00,2020-03-31 00:00:00,2021-03-31 00:00:00,2022-03-31 00:00:00,2023-03-31 00:00:00,2024-03-31 00:00:00,2025-03-31 00:00:00,2026-03-31 00:00:00,Trailing,Best Case,Worst Case
0,Sales,13260.83,16119.77,19778.52,21052.0,21644.0,28799,40575,51084,60456,87584,87584,126884.958581,108023.855123
1,Expenses,12096.93,14475.57,17784.73,18589.0,19919.0,25455,35693,45792,54762,79227,79228,114559.293399,97717.779431
2,Operating Profit,1163.90,1644.20,1993.79,2463.0,1725.0,3344,4882,5292,5694,8357,8356,12325.665183,10306.075692
3,Other Income,-42.38,69.93,178.48,153.0,180.0,177,306,534,487,450,452,0,0
4,Depreciation,110.53,131.43,162.84,348.0,375.0,399,441,584,693,826,826,826,826

In [5]:
# Check column names
print(profit_loss.columns.tolist())

['Narration', datetime.datetime(2017, 3, 31, 0, 0), datetime.datetime(2018, 3, 31, 0, 0), datetime.datetime(2019, 3, 31, 0, 0), datetime.datetime(2020, 3, 31, 0, 0), datetime.datetime(2021, 3, 31, 0, 0), datetime.datetime(2022, 3, 31, 0, 0), datetime.datetime(2023, 3, 31, 0, 0), datetime.datetime(2024, 3, 31, 0, 0), datetime.datetime(2025, 3, 31, 0, 0), datetime.datetime(2026, 3, 31, 0, 0), 'Trailing', 'Best Case', 'Worst Case']

In [6]:
# Removing unwanted columns #
profit_loss = profit_loss.drop(columns=["Trailing", "Best Case", "Worst Case"])

# Renaming Date columns to FY format #
new_columns = ["Narration"] + [f"FY{col.year}" for col in profit_loss.columns[1:]]
profit_loss.columns = new_columns

print(profit_loss.columns.tolist())

['Narration', 'FY2017', 'FY2018', 'FY2019', 'FY2020', 'FY2021', 'FY2022', 'FY2023', 'FY2024', 'FY2025', 'FY2026']

In [7]:
balance_sheet = pd.read_excel("Titan Company.xlsx", sheet_name="Balance Sheet",header=2)

balance_sheet = balance_sheet.drop(columns=["Trailing", "Best Case", "Worst Case"], errors="ignore")
new_columns = ["Narration"] + [f'FY{col.year}' for col in balance_sheet.columns[1:] if hasattr(col, "year")]
balance_sheet.columns = new_columns[:len(balance_sheet.columns)]

print(balance_sheet.columns.tolist())

['Narration', 'FY2017', 'FY2018', 'FY2019', 'FY2020', 'FY2021', 'FY2022', 'FY2023', 'FY2024', 'FY2025', 'FY2026']

In [8]:
# Check if Balance Sheet has actual data in FY2017
print(balance_sheet[['Narration', 'FY2017', 'FY2018', 'FY2019']].head(10))

                  Narration   FY2017   FY2018    FY2019
0      Equity Share Capital    88.78    88.78     88.78
1                  Reserves  4143.60  5001.10   5981.37
2                Borrowings  1882.43  1691.01   2392.98
3         Other Liabilities  2292.76  2740.15   3246.71
4                     Total  8407.57  9521.04  11709.84
5                       NaN      NaN      NaN       NaN
6                 Net Block  1188.72  1473.81   1566.63
7  Capital Work in Progress   152.07    43.37     31.77
8               Investments   430.73    35.99    108.42
9              Other Assets  6636.05  7967.87  10003.02

In [9]:
# Check all NaN rows in balance sheet
print(balance_sheet.isnull().all(axis=1).sum(), "fully empty rows found")

# See which rows are NaN
print(balance_sheet)

4 fully empty rows found
                   Narration       FY2017       FY2018        FY2019  \
0       Equity Share Capital    88.780000    88.780000     88.780000
1                   Reserves  4143.600000  5001.100000   5981.370000
2                 Borrowings  1882.430000  1691.010000   2392.980000
3          Other Liabilities  2292.760000  2740.150000   3246.710000
4                      Total  8407.570000  9521.040000  11709.840000
5                        NaN          NaN          NaN           NaN
6                  Net Block  1188.720000  1473.810000   1566.630000
7   Capital Work in Progress   152.070000    43.370000     31.770000
8                Investments   430.730000    35.990000    108.420000
9               Other Assets  6636.050000  7967.870000  10003.020000
10                     Total  8407.570000  9521.040000  11709.840000
11                       NaN          NaN          NaN           NaN
12           Working Capital  4343.290000  5227.720000   6756.310000
13                   Debtors   207.600000   295.690000    420.450000
14                 Inventory  4925.740000  5924.840000   7038.820000
15                       NaN          NaN          NaN           NaN
16               Debtor Days     5.714122     6.695310      7.759137
17        Inventory Turnover     2.692150     2.720710      2.809920
18                       NaN          NaN          NaN           NaN
19          Return on Equity     0.168102     0.222027      0.231320
20     Return on Capital Emp          NaN     0.245462      0.263635

          FY2020        FY2021        FY2022        FY2023        FY2024  \
0      89.000000     89.000000     89.000000     89.000000     89.000000
1    6580.000000   7408.000000   9214.000000  11762.000000   9304.000000
2    3562.000000   5638.000000   7275.000000   9367.000000  15528.000000
3    3313.000000   3309.000000   4610.000000   5802.000000   6626.000000
4   13544.000000  16444.000000  21188.000000  27020.000000  31547.000000
5            NaN           NaN           NaN           NaN           NaN
6    2633.000000   2523.000000   2544.000000   2998.000000   3709.000000
7      18.000000     32.000000     85.000000    144.000000     97.000000
8     158.000000   2824.000000    294.000000   2515.000000   2345.000000
9   10735.000000  11065.000000  18265.000000  21363.000000  25396.000000
10  13544.000000  16444.000000  21188.000000  27020.000000  31547.000000
11           NaN           NaN           NaN           NaN           NaN
12   7422.000000   7756.000000  13655.000000  15561.000000  18770.000000
13    312.000000    366.000000    565.000000    674.000000   1018.000000
14   8103.000000   8408.000000  13609.000000  16584.000000  19051.000000
15           NaN           NaN           NaN           NaN           NaN
16      5.409462      6.172149      7.160839      6.063093      7.273706
17      2.598050      2.574215      2.116173      2.446635      2.681434
18           NaN           NaN           NaN           NaN           NaN
19      0.225071      0.129785      0.233581      0.274238      0.372192
20      0.242643      0.130960      0.210144      0.251191      0.227226

          FY2025        FY2026
0      89.000000     89.000000
1   11535.000000  15614.000000
2   20777.000000  30621.000000
3    8244.000000  14237.000000
4   40645.000000  60561.000000
5            NaN           NaN
6    4062.000000   6878.000000
7     105.000000    163.000000
8    1988.000000   3506.000000
9   34490.000000  50014.000000
10  40645.000000  60561.000000
11           NaN           NaN
12  26246.000000  35777.000000
13   1068.000000    916.000000
14  28184.000000  42743.000000
15           NaN           NaN
16      6.447995      3.817364
17      2.145047      2.049084
18           NaN           NaN
19      0.287078      0.323059
20      0.191480      0.202756

In [10]:
# Remove rows where ALL values are NaN
balance_sheet = balance_sheet.dropna(how='all')

# Check how many rows remain
print("Rows remaining:", len(balance_sheet))
print()
print(balance_sheet)

Rows remaining: 17

                   Narration       FY2017       FY2018        FY2019  \
0       Equity Share Capital    88.780000    88.780000     88.780000
1                   Reserves  4143.600000  5001.100000   5981.370000
2                 Borrowings  1882.430000  1691.010000   2392.980000
3          Other Liabilities  2292.760000  2740.150000   3246.710000
4                      Total  8407.570000  9521.040000  11709.840000
6                  Net Block  1188.720000  1473.810000   1566.630000
7   Capital Work in Progress   152.070000    43.370000     31.770000
8                Investments   430.730000    35.990000    108.420000
9               Other Assets  6636.050000  7967.870000  10003.020000
10                     Total  8407.570000  9521.040000  11709.840000
12           Working Capital  4343.290000  5227.720000   6756.310000
13                   Debtors   207.600000   295.690000    420.450000
14                 Inventory  4925.740000  5924.840000   7038.820000
16               Debtor Days     5.714122     6.695310      7.759137
17        Inventory Turnover     2.692150     2.720710      2.809920
19          Return on Equity     0.168102     0.222027      0.231320
20     Return on Capital Emp          NaN     0.245462      0.263635

          FY2020        FY2021        FY2022        FY2023        FY2024  \
0      89.000000     89.000000     89.000000     89.000000     89.000000
1    6580.000000   7408.000000   9214.000000  11762.000000   9304.000000
2    3562.000000   5638.000000   7275.000000   9367.000000  15528.000000
3    3313.000000   3309.000000   4610.000000   5802.000000   6626.000000
4   13544.000000  16444.000000  21188.000000  27020.000000  31547.000000
6    2633.000000   2523.000000   2544.000000   2998.000000   3709.000000
7      18.000000     32.000000     85.000000    144.000000     97.000000
8     158.000000   2824.000000    294.000000   2515.000000   2345.000000
9   10735.000000  11065.000000  18265.000000  21363.000000  25396.000000
10  13544.000000  16444.000000  21188.000000  27020.000000  31547.000000
12   7422.000000   7756.000000  13655.000000  15561.000000  18770.000000
13    312.000000    366.000000    565.000000    674.000000   1018.000000
14   8103.000000   8408.000000  13609.000000  16584.000000  19051.000000
16      5.409462      6.172149      7.160839      6.063093      7.273706
17      2.598050      2.574215      2.116173      2.446635      2.681434
19      0.225071      0.129785      0.233581      0.274238      0.372192
20      0.242643      0.130960      0.210144      0.251191      0.227226

          FY2025        FY2026
0      89.000000     89.000000
1   11535.000000  15614.000000
2   20777.000000  30621.000000
3    8244.000000  14237.000000
4   40645.000000  60561.000000
6    4062.000000   6878.000000
7     105.000000    163.000000
8    1988.000000   3506.000000
9   34490.000000  50014.000000
10  40645.000000  60561.000000
12  26246.000000  35777.000000
13   1068.000000    916.000000
14  28184.000000  42743.000000
16      6.447995      3.817364
17      2.145047      2.049084
19      0.287078      0.323059
20      0.191480      0.202756

In [11]:
# Check for any remaining NaN values
print("Remaining NaN values:")
print(balance_sheet.isnull().sum())
print()
print("Shape:", balance_sheet.shape)
print()
print(balance_sheet['Narration'].tolist())

Remaining NaN values:
Narration    0
FY2017       1
FY2018       0
FY2019       0
FY2020       0
FY2021       0
FY2022       0
FY2023       0
FY2024       0
FY2025       0
FY2026       0
dtype: int64

Shape: (17, 11)

['Equity Share Capital', 'Reserves', 'Borrowings', 'Other Liabilities', 'Total', 'Net Block', 'Capital Work in Progress', 'Investments', 'Other Assets', 'Total', 'Working Capital', 'Debtors', 'Inventory', 'Debtor Days', 'Inventory Turnover', 'Return on Equity', 'Return on Capital Emp']

In [12]:
# Find which row has NaN in FY2017
print(balance_sheet[balance_sheet['FY2017'].isnull()])

                Narration  FY2017    FY2018    FY2019    FY2020   FY2021  \
20  Return on Capital Emp     NaN  0.245462  0.263635  0.242643  0.13096

      FY2022    FY2023    FY2024   FY2025    FY2026
20  0.210144  0.251191  0.227226  0.19148  0.202756

In [13]:
# Check which index positions have 'Total'
print(balance_sheet[balance_sheet['Narration'] == 'Total'])

   Narration   FY2017   FY2018    FY2019   FY2020   FY2021   FY2022   FY2023  \
4      Total  8407.57  9521.04  11709.84  13544.0  16444.0  21188.0  27020.0
10     Total  8407.57  9521.04  11709.84  13544.0  16444.0  21188.0  27020.0

     FY2024   FY2025   FY2026
4   31547.0  40645.0  60561.0
10  31547.0  40645.0  60561.0

In [14]:
# Renaming the Total Rows #
balance_sheet.loc[4, 'Narration'] = 'Total_Liabilities_And_Equity'
balance_sheet.loc[10, 'Narration']= "Total_Assets"

print(balance_sheet['Narration'].tolist())

['Equity Share Capital', 'Reserves', 'Borrowings', 'Other Liabilities', 'Total_Liabilities_And_Equity', 'Net Block', 'Capital Work in Progress', 'Investments', 'Other Assets', 'Total_Assets', 'Working Capital', 'Debtors', 'Inventory', 'Debtor Days', 'Inventory Turnover', 'Return on Equity', 'Return on Capital Emp']

In [15]:
print(type(balance_sheet))

<class 'pandas.core.frame.DataFrame'>

In [16]:
print("P&L columns:", profit_loss.columns.tolist())
print()
print("Cash Flow columns:", cash_flow.columns.tolist())

P&L columns: ['Narration', 'FY2017', 'FY2018', 'FY2019', 'FY2020', 'FY2021', 'FY2022', 'FY2023', 'FY2024', 'FY2025', 'FY2026']

Cash Flow columns: ['TITAN COMPANY LTD', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'SCREENER.IN', 'Unnamed: 10']

In [17]:
# Reload Cash Flow with correct header3
cash_flow = pd.read_excel("Titan Company.xlsx", sheet_name="Cash Flow", header=2)

# Remove empty rows #
cash_flow = cash_flow.dropna(how='all')

# Remove Trailing/Best/Worst if they exist #
cash_flow = cash_flow.drop(columns=['Trailing', 'Best Case', 'Worst Case'], errors='ignore')

# Fix column names to FY format #
new_columns = ['Narration'] + [f'FY{col.year}' for col in cash_flow.columns[1:] if hasattr(col, 'year')]
cash_flow.columns = new_columns[:len(cash_flow.columns)]

# Verify #
print("Cash Flow columns:", cash_flow.columns.tolist())
print()
print("Cash Flow Narration:", cash_flow['Narration'].tolist())

Cash Flow columns: ['Narration', 'FY2017', 'FY2018', 'FY2019', 'FY2020', 'FY2021', 'FY2022', 'FY2023', 'FY2024', 'FY2025', 'FY2026']

Cash Flow Narration: ['Cash from Operating Activity', 'Cash from Investing Activity', 'Cash from Financing Activity', 'Net Cash Flow']

In [18]:
# Save all cleaned sheets to a new Excel file

with pd.ExcelWriter("Titan_Cleaned.xlsx") as writer:
    profit_loss.to_excel(writer, sheet_name="Profit_Loss", index=False)
    balance_sheet.to_excel(writer, sheet_name="Balance_Sheet", index=False)
    cash_flow.to_excel(writer, sheet_name="Cash_Flow", index=False)

print("Cleaned data saved successfully!! ✅")

Cleaned data saved successfully!! ✅

In [19]:
import pandas as pd

# Load the cleaned file
profit_loss = pd.read_excel("Titan_Cleaned.xlsx", sheet_name="Profit_Loss")
balance_sheet = pd.read_excel("Titan_Cleaned.xlsx", sheet_name="Balance_Sheet")
cash_flow = pd.read_excel("Titan_Cleaned.xlsx", sheet_name="Cash_Flow")

print("All cleaned sheets loaded successfully!! ✅")
print()
print("P&L Shape:", profit_loss.shape)
print("Balance Sheet Shape:", balance_sheet.shape)
print("Cash Flow Shape:", cash_flow.shape)

All cleaned sheets loaded successfully!! ✅

P&L Shape: (22, 11)
Balance Sheet Shape: (17, 11)
Cash Flow Shape: (4, 11)

In [20]:
print(profit_loss['Narration'].tolist())

['Sales', 'Expenses', 'Operating Profit', 'Other Income', 'Depreciation', 'Interest', 'Profit before tax', 'Tax', 'Net profit', 'EPS', 'Price to earning', 'Price', nan, 'RATIOS:', 'Dividend Payout', 'OPM', nan, nan, nan, nan, nan, nan]

In [21]:
# Keep only actual P&L rows
rows_to_keep = ['Sales', 'Expenses', 'Operating Profit', 
                'Other Income', 'Depreciation', 'Interest', 
                'Profit before tax', 'Tax', 'Net profit', 'EPS']

profit_loss = profit_loss[profit_loss['Narration'].isin(rows_to_keep)]

# Reset index
profit_loss = profit_loss.reset_index(drop=True)

# Verify
print(profit_loss['Narration'].tolist())
print("Shape:", profit_loss.shape)

['Sales', 'Expenses', 'Operating Profit', 'Other Income', 'Depreciation', 'Interest', 'Profit before tax', 'Tax', 'Net profit', 'EPS']
Shape: (10, 11)

In [ ]:
# Fix missing Year column
titan_pl = titan_pl.reset_index()
titan_pl = titan_pl.rename(columns={'index': 'Year'})

# Verify
print(titan_pl.columns.tolist())

In [ ]:
# ── FINAL PYTHON BLOCK ──────────────────────────

# Step 1 — Fix P&L numeric columns
year_cols = ['Revenue', 'Expenses', 'Operating_Profit', 'Other_Income', 
             'Depreciation', 'Interest', 'PBT', 'Net_Profit', 'EPS', 'EBITDA']
titan_pl[year_cols] = titan_pl[year_cols].apply(pd.to_numeric, errors='coerce')

# Step 2 — Calculate columns
titan_pl['Net_Profit_Margin'] = (titan_pl['Net_Profit'] / titan_pl['Revenue'] * 100).round(2)
titan_pl['YoY_Revenue_Growth'] = (titan_pl['Revenue'].pct_change() * 100).round(2)

# Step 3 — Fix Balance Sheet numeric columns
bs_cols = balance_sheet.columns[1:].tolist()
balance_sheet[bs_cols] = balance_sheet[bs_cols].apply(pd.to_numeric, errors='coerce')

# Step 4 — Save everything
with pd.ExcelWriter("Titan_Final.xlsx") as writer:
    titan_pl.to_excel(writer, sheet_name="Profit_Loss", index=False)
    balance_sheet.to_excel(writer, sheet_name="Balance_Sheet", index=False)
    cash_flow.to_excel(writer, sheet_name="Cash_Flow", index=False)

print("PYTHON PHASE COMPLETE!! 🎉")
print("Titan_Final.xlsx saved successfully!!")
print()
print(titan_pl[['Year', 'Revenue', 'Net_Profit', 'Net_Profit_Margin', 'YoY_Revenue_Growth']])

In [ ]:
import pandas as pd

# Read from Titan_Final and save as CSVs
pl = pd.read_excel("Titan_Final.xlsx", sheet_name="Profit_Loss")
bs = pd.read_excel("Titan_Final.xlsx", sheet_name="Balance_Sheet")
cf = pd.read_excel("Titan_Final.xlsx", sheet_name="Cash_Flow")

pl.to_csv("Titan_PL.csv", index=False)
bs.to_csv("Titan_BS.csv", index=False)
cf.to_csv("Titan_CF.csv", index=False)

print("3 CSV files ready!! ✅")

In [ ]:
import os
print(os.listdir())

In [ ]:
import pandas as pd

# Read Titan_Final
pl = pd.read_excel("Titan_Final.xlsx", sheet_name="Profit_Loss")

# Check for duplicate columns
print(pl.columns.tolist())
print("Duplicates:", pl.columns[pl.columns.duplicated()].tolist())

In [23]:
import pandas as pd

pl = pd.read_excel("Titan_Final.xlsx", sheet_name="Profit_Loss")
print(pl[pl['Year'] == 'FY2017'])

     Year   Revenue  Expenses  Operating_Profit  Other_Income  Depreciation  \
0  FY2017  13260.83  12096.93            1163.9        -42.38        110.53

   Interest     PBT  Net_Profit       EPS   EBITDA  Net_Profit_Margin  \
0     37.74  973.25      711.47  8.013854  1274.43               5.37

   YoY_Revenue_Growth
0                 NaN